"""
pipeline.py — MedDRA Coding Pipeline
Dataset: MedDRA_LLT_PT_v28.1.xlsx  (LLT Code | Decode | PT Code)
Model  : openai/gpt-oss-120b via Euron
Agent  : LangGraph StateGraph + ToolNode
Search : 3-Tier Hybrid — Fuzzy → BM25 → Vector (fastembed, no torch)
Events : adverse_event | device_issue | medication_error | product_quality | lack_of_efficacy | other
"""

import os, re, json, pickle
import pandas as pd
import numpy as np
import nltk
from typing import List, Dict
from contextlib import redirect_stdout, redirect_stderr
from io import StringIO

# ─── Search libraries ─────────────────────────────────────────────────────────
from rapidfuzz import process, fuzz
from rank_bm25 import BM25Okapi
from fastembed import TextEmbedding
import faiss

# ─── LangChain / LangGraph ────────────────────────────────────────────────────
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, MessagesState, START
from langgraph.prebuilt import ToolNode, tools_condition

# ─── Pydantic ─────────────────────────────────────────────────────────────────
from pydantic import BaseModel, Field

nltk.download("punkt",     quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("stopwords", quiet=True)
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


# ─── Pydantic output model ────────────────────────────────────────────────────
class LLTResult(BaseModel):
    verbatim:    str   = Field(..., description="Exact patient phrase")
    event_type:  str   = Field(..., description="adverse_event | device_issue | medication_error | product_quality | lack_of_efficacy | other")
    decode:      str   = Field(..., description="Matched MedDRA Decode term")
    llt_code:    int   = Field(..., description="MedDRA LLT Code")
    pt_code:     int   = Field(..., description="MedDRA PT Code")
    search_tier: str   = Field(..., description="fuzzy | bm25 | vector | fuzzy_fallback")
    confidence:  float = Field(..., description="Match confidence score")


# ─── Config ───────────────────────────────────────────────────────────────────
EXCEL_FILE        = "MedDRA_LLT_PT_v28.1.xlsx"
EURON_BASE_URL    = "https://api.euron.one/api/v1/euri"
MODEL_NAME        = "openai/gpt-oss-120b"

COL_LLT_CODE      = "LLT Code"
COL_DECODE        = "Decode"
COL_PT_CODE       = "PT Code"

FUZZY_THRESHOLD   = 85
BM25_THRESHOLD    = 3.0
VECTOR_TOP_N      = 3
EMBED_MODEL_NAME  = "BAAI/bge-small-en-v1.5"

# Prebuilt cache files (generated by preload.py)
BM25_CACHE_PATH   = "bm25_index.pkl"
VECTOR_INDEX_PATH = "meddra_faiss.index"
VECTOR_META_PATH  = "meddra_faiss_meta.pkl"
FASTEMBED_CACHE   = "./fastembed_cache"

STOP_WORDS        = set(stopwords.words("english"))


# ─── Globals ──────────────────────────────────────────────────────────────────
llt_df            = None
bm25_index        = None
decode_list_clean = None
embed_model       = None
faiss_index       = None
faiss_meta        = None
llm               = None
agent             = None


# ─── Prompts ──────────────────────────────────────────────────────────────────
_VERBATIM_PROMPT = """
You are a senior Pharmacovigilance specialist with expertise in adverse event
reporting, medical device vigilance, and medication error detection.

Your job: extract ALL reportable events from the patient narrative and categorize each one.

EVENT TYPES:
─────────────────────────────────────────────────────────────────
1. adverse_event     → Any symptom, reaction, or side effect
                       e.g. "head was pounding", "skin turned red", "felt dizzy"

2. device_issue      → Problem with a medical device or delivery system
                       e.g. "pump stopped working", "needle broke", "patch fell off",
                            "pen device leaked", "infusion set blocked"

3. medication_error  → Wrong dose, missed dose, accidental overdose, wrong route
                       e.g. "took double the dose", "given wrong medication",
                            "missed my morning dose", "injected in wrong site"

4. product_quality   → Contamination, packaging defect, unusual appearance
                       e.g. "tablet was discoloured", "found particles in vial",
                            "packaging was already open", "strange smell from tablet"

5. lack_of_efficacy  → Drug not working as expected
                       e.g. "pain did not go away", "blood sugar still high",
                            "no improvement after 3 days"

6. other             → Anything else reportable but not fitting above
─────────────────────────────────────────────────────────────────

Rules:
- Extract verbatim — patient's EXACT words. Do NOT rephrase or interpret.
- Capture ALL event types present, not just symptoms.
- Each extracted term must map to ONE event type.
- Return ONLY a valid JSON array. No other text whatsoever.

Output format:
[
  {"verbatim": "exact phrase", "event_type": "adverse_event"},
  {"verbatim": "exact phrase", "event_type": "device_issue"}
]

Examples:
  Input: "The pump kept beeping and stopped delivering insulin. I panicked and
          took an extra dose. After that my hands were shaking badly."
  Output: [
    {"verbatim": "pump kept beeping and stopped delivering insulin", "event_type": "device_issue"},
    {"verbatim": "took an extra dose",                               "event_type": "medication_error"},
    {"verbatim": "hands were shaking badly",                         "event_type": "adverse_event"}
  ]

  Input: "The tablet looked different and had a strange smell. I took it anyway
          and felt nauseous. My sugar levels didn't improve at all."
  Output: [
    {"verbatim": "tablet looked different and had a strange smell", "event_type": "product_quality"},
    {"verbatim": "felt nauseous",                                   "event_type": "adverse_event"},
    {"verbatim": "sugar levels didn't improve at all",              "event_type": "lack_of_efficacy"}
  ]
"""

_AGENT_SYSTEM_PROMPT = """
You are a MedDRA coding specialist for Pharmacovigilance.

You will receive a list of objects with verbatim terms and their event_type.
For EACH item, call search_llt_tool with the verbatim and use the top_match result.

Return ONLY a valid JSON array — no explanation, no markdown, no reasoning text:
[
  {
    "verbatim":    "exact patient phrase",
    "event_type":  "adverse_event | device_issue | medication_error | product_quality | lack_of_efficacy | other",
    "decode":      "matched MedDRA Decode term",
    "llt_code":    12345678,
    "pt_code":     12345678,
    "search_tier": "fuzzy | bm25 | vector | fuzzy_fallback",
    "confidence":  85.5
  }
]
"""


# ─── Init pipeline ────────────────────────────────────────────────────────────
def init_pipeline(api_key: str, excel_path: str = EXCEL_FILE):
    global llt_df, bm25_index, decode_list_clean
    global embed_model, faiss_index, faiss_meta, llm, agent

    # Tell fastembed to use local cache folder — no re-download
    os.environ["FASTEMBED_CACHE_PATH"] = FASTEMBED_CACHE

    # ── 1. Load Excel ─────────────────────────────────────────────
    llt_df = pd.read_excel(excel_path)
    llt_df.columns = llt_df.columns.str.strip()

    assert COL_LLT_CODE in llt_df.columns, f"Missing column: {COL_LLT_CODE}"
    assert COL_DECODE   in llt_df.columns, f"Missing column: {COL_DECODE}"
    assert COL_PT_CODE  in llt_df.columns, f"Missing column: {COL_PT_CODE}"

    llt_df["DECODE_CLEAN"] = llt_df[COL_DECODE].str.strip().str.lower()
    decode_list_clean = llt_df["DECODE_CLEAN"].tolist()

    # ── 2. Load BM25 from cache or build fresh ────────────────────
    if os.path.exists(BM25_CACHE_PATH):
        with open(BM25_CACHE_PATH, "rb") as f:
            bm25_index = pickle.load(f)
    else:
        tokenized  = [_tokenize(n) for n in decode_list_clean]
        bm25_index = BM25Okapi(tokenized)
        with open(BM25_CACHE_PATH, "wb") as f:
            pickle.dump(bm25_index, f)

    # ── 3. Load fastembed from cache ──────────────────────────────
    embed_model = TextEmbedding(EMBED_MODEL_NAME)

    # ── 4. Load FAISS from cache or build fresh ───────────────────
    faiss_index, faiss_meta = _build_or_load_faiss()

    # ── 5. LLM ────────────────────────────────────────────────────
    llm = ChatOpenAI(
        model=MODEL_NAME,
        api_key=api_key,
        base_url=EURON_BASE_URL,
        temperature=0,
        max_tokens=1500,
    )

    # ── 6. Build LangGraph agent ──────────────────────────────────
    _build_agent()


# ─── Build agent (separate so progress bar can call it) ───────────────────────
def _build_agent():
    global agent

    llm_with_tools = llm.bind_tools([search_llt_tool])

    def call_model(state: MessagesState):
        sys_msg  = SystemMessage(content=_AGENT_SYSTEM_PROMPT)
        response = llm_with_tools.invoke([sys_msg] + state["messages"])
        return {"messages": [response]}

    tool_node = ToolNode([search_llt_tool])

    builder = StateGraph(MessagesState)
    builder.add_node("agent", call_model)
    builder.add_node("tools", tool_node)
    builder.add_edge(START, "agent")
    builder.add_conditional_edges("agent", tools_condition)
    builder.add_edge("tools", "agent")

    agent = builder.compile()


# ─── Helpers ──────────────────────────────────────────────────────────────────
def _tokenize(text: str) -> List[str]:
    tokens = word_tokenize(str(text).lower())
    return [t for t in tokens if t.isalpha() and t not in STOP_WORDS]


def _row_to_dict(idx: int, score: float, method: str) -> Dict:
    row = llt_df.iloc[idx]
    return {
        "decode":      row[COL_DECODE],
        "llt_code":    int(row[COL_LLT_CODE]),
        "pt_code":     int(row[COL_PT_CODE]),
        "score":       round(float(score), 4),
        "method":      method,
    }


def _build_or_load_faiss():
    if os.path.exists(VECTOR_INDEX_PATH) and os.path.exists(VECTOR_META_PATH):
        index = faiss.read_index(VECTOR_INDEX_PATH)
        with open(VECTOR_META_PATH, "rb") as f:
            meta = pickle.load(f)
        return index, meta

    # Build fresh if cache missing
    names      = llt_df[COL_DECODE].tolist()
    embeddings = np.array(list(embed_model.embed(names)), dtype="float32")
    faiss.normalize_L2(embeddings)

    index = faiss.IndexFlatIP(embeddings.shape[1])
    index.add(embeddings)
    faiss.write_index(index, VECTOR_INDEX_PATH)

    meta = {
        "decodes":   llt_df[COL_DECODE].tolist(),
        "llt_codes": llt_df[COL_LLT_CODE].tolist(),
        "pt_codes":  llt_df[COL_PT_CODE].tolist(),
    }
    with open(VECTOR_META_PATH, "wb") as f:
        pickle.dump(meta, f)
    return index, meta


# ─── Tier 1: Fuzzy ───────────────────────────────────────────────────────────
def _fuzzy_search(verbatim: str) -> List[Dict]:
    results = process.extract(
        verbatim.lower(),
        decode_list_clean,
        scorer=fuzz.token_sort_ratio,
        limit=3,
    )
    return [_row_to_dict(idx, score, "fuzzy") for _, score, idx in results]


# ─── Tier 2: BM25 ────────────────────────────────────────────────────────────
def _bm25_search(verbatim: str) -> List[Dict]:
    tokens = _tokenize(verbatim)
    if not tokens:
        return []
    scores   = bm25_index.get_scores(tokens)
    top_idxs = np.argsort(scores)[::-1][:5]
    return [
        _row_to_dict(idx, scores[idx], "bm25")
        for idx in top_idxs if scores[idx] > 0
    ]


# ─── Tier 3: Vector ──────────────────────────────────────────────────────────
def _vector_search(verbatim: str) -> List[Dict]:
    qvec = np.array(list(embed_model.embed([verbatim])), dtype="float32")
    faiss.normalize_L2(qvec)
    scores, indices = faiss_index.search(qvec, VECTOR_TOP_N)
    output = []
    for score, idx in zip(scores[0], indices[0]):
        if idx == -1:
            continue
        output.append({
            "decode":   faiss_meta["decodes"][idx],
            "llt_code": int(faiss_meta["llt_codes"][idx]),
            "pt_code":  int(faiss_meta["pt_codes"][idx]),
            "score":    round(float(score), 4),
            "method":   "vector",
        })
    return output


# ─── Hybrid router ───────────────────────────────────────────────────────────
def hybrid_search(verbatim: str) -> Dict:
    # Tier 1 — Fuzzy
    fuzzy = _fuzzy_search(verbatim)
    if fuzzy and fuzzy[0]["score"] >= FUZZY_THRESHOLD:
        return {"verbatim": verbatim, "top_match": fuzzy[0], "search_used": "fuzzy"}

    # Tier 2 — BM25
    bm25 = _bm25_search(verbatim)
    if bm25 and bm25[0]["score"] >= BM25_THRESHOLD:
        return {"verbatim": verbatim, "top_match": bm25[0], "search_used": "bm25"}

    # Tier 3 — Vector
    vector = _vector_search(verbatim)
    if vector:
        return {"verbatim": verbatim, "top_match": vector[0], "search_used": "vector"}

    # Fallback
    return {
        "verbatim":    verbatim,
        "top_match":   fuzzy[0] if fuzzy else None,
        "search_used": "fuzzy_fallback",
    }


# ─── LangChain Tool ───────────────────────────────────────────────────────────
@tool
def search_llt_tool(verbatim: str) -> str:
    """
    Search MedDRA LLT dataset for a verbatim symptom or event term.
    Uses 3-tier hybrid search: Fuzzy → BM25 → Vector.
    Returns matched Decode, LLT Code, PT Code.
    Input: single verbatim string.
    """
    return json.dumps(hybrid_search(verbatim))


# ─── Verbatim extractor ───────────────────────────────────────────────────────
def extract_verbatim(narrative: str) -> List[Dict]:
    """Returns list of dicts: [{verbatim, event_type}, ...]"""
    messages = [
        SystemMessage(content=_VERBATIM_PROMPT),
        HumanMessage(content=f"Narrative:\n{narrative}"),
    ]
    resp = llm.invoke(messages)
    raw  = re.sub(r"```json|```", "", resp.content.strip()).strip()
    try:
        result = json.loads(raw)
        assert isinstance(result, list)
        # Normalize — handle plain strings and dicts
        normalized = []
        for item in result:
            if isinstance(item, str):
                normalized.append({"verbatim": item, "event_type": "adverse_event"})
            elif isinstance(item, dict):
                normalized.append(item)
        return normalized
    except Exception:
        return []


# ─── Main pipeline ────────────────────────────────────────────────────────────
def run_pipeline(narrative: str) -> List[LLTResult]:
    """
    Full silent pipeline:
    Narrative → Verbatim + Event Type → MedDRA LLT Code
    Returns clean list of LLTResult. All agent noise suppressed.
    """
    extracted = extract_verbatim(narrative)
    if not extracted:
        return []

    agent_input = f"Match these terms to MedDRA LLTs: {json.dumps(extracted)}"

    with redirect_stdout(StringIO()), redirect_stderr(StringIO()):
        output = agent.invoke({"messages": [HumanMessage(content=agent_input)]})

    raw = output["messages"][-1].content.strip()

    # Strip reasoning text before JSON array
    json_start = raw.find("[")
    json_end   = raw.rfind("]")
    if json_start != -1 and json_end != -1:
        raw = raw[json_start: json_end + 1]

    raw = re.sub(r"```json|```", "", raw).strip()

    try:
        coded = json.loads(raw)
        return [LLTResult(**item) for item in coded if isinstance(item, dict)]
    except Exception:
        return []


# ─── Lookup helper ────────────────────────────────────────────────────────────
def lookup_llt(search_value: str) -> pd.DataFrame:
    """Search by LLT Code, PT Code, or partial Decode name."""
    search_value = str(search_value).strip()
    if search_value.isdigit():
        code      = int(search_value)
        by_llt    = llt_df[llt_df[COL_LLT_CODE] == code]
        by_pt     = llt_df[llt_df[COL_PT_CODE]  == code]
        result    = pd.concat([by_llt, by_pt]).drop_duplicates()
    else:
        result = llt_df[
            llt_df[COL_DECODE].str.contains(search_value, case=False, na=False)
        ]
    return result[[COL_LLT_CODE, COL_DECODE, COL_PT_CODE]].reset_index(drop=True)
